# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zombie_admin}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julien Portalier"]
  s.date = %q{2011-09-20}
  s.description = %q{Administration engine for Ruby on Rails.}
  s.email = %q{ysbaddaden@gmail.com}
  s.files = [
    "app/views/layouts/zombie_admin.html.erb",
    "app/views/zombie_admin/_filters.html.erb",
    "app/views/zombie_admin/_resource.html.erb",
    "app/views/zombie_admin/_scopes.html.erb",
    "app/views/zombie_admin/index.html.erb",
    "app/views/zombie_admin/show.html.erb",
    "lib/zombie_admin.rb",
    "lib/zombie_admin/config.rb",
    "lib/zombie_admin/controllers/application.rb",
    "lib/zombie_admin/controllers/resources.rb",
    "lib/zombie_admin/controllers/responder.rb",
    "lib/zombie_admin/resource.rb",
    "lib/zombie_admin/resource/dsl.rb",
    "lib/zombie_admin/resource/menu.rb",
    "lib/zombie_admin/resource/naming.rb",
    "lib/zombie_admin/resource/scope.rb",
    "lib/zombie_admin/routes.rb"
  ]
  s.homepage = %q{http://github.com/ysbaddaden/calliope}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Administration engine for Ruby on Rails.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0"])
  end
end

